; NFSMW Slingshot Feature by Kevin4e
; GitHub page: https://github.com/Kevin4e/NFSMWSlingshotFeature

[Main]
Enable = true                                    ; Enable script (true/1/on/yes = enabled, false/0/off/no = disabled)

[SlingshotAttributes]
SlingshotMode = 0                                ; 0 = arcade-style (post-drafting boost), 1 = realistic-style (while-drafting boost)
MaxSlingshotBoost = 1.0                          ; Maximum slingshot boost value
ProgressiveBoostMultiplier = 1.0                 ; Multiplier applied while boost is growing
FinalBoostMultiplier = 1.0                       ; Multiplier applied while boost is on release

[BoostRanges]
MaxLongitudinalDistance = 35.0                   ; Maximum longitudinal distance (game units) for boost growth
MaxLateralDistance = 1.5                         ; Maximum lateral distance (game units) for boost growth

[Debug]
UseSpeedbreakerBarAsSlingshotMeter = false       ; (EXPERIMENTAL) Displays the slingshot boost in the speedbreaker bar (true/1/on/yes = enabled, false/0/off/no = disabled)