; NFSMW Slingshot Feature by Kevin4e
; GitHub page: https://github.com/Kevin4e/NFSMWSlingshotFeature

[Main]
Enable = true                                    ; Enable script (true/1/on/yes = enabled, false/0/off/no = disabled)

[SlingshotAttributes]
SlingshotMode = 0                                ; 0 = arcade-style (post-drafting boost), 1 = realistic-style (while-drafting boost)
MaxSlingshotBoost = 1.0                          ; Maximum slingshot boost value
ProgressiveBoostMultiplier = 1.0                 ; Multiplier applied while boost is growing
FinalBoostMultiplier = 1.0                       ; Multiplier applied while boost is on release
DecayBoostMultiplier = 1.0                       ; Multiplier applied while boost is decaying
MinimumSpeedForMaxDraftGain = 300.0              ; Minimum speed to maximize the slingshot gain (KM/H) (OFF = Draft gain does NOT depend on speed)

[BoostRanges]
MaxLongitudinalDistance = 45.0                   ; Maximum longitudinal distance (game units) for boost growth
MaxLateralDistance = AUTO                        ; Maximum lateral distance (game units) for boost growth (AUTO = Use AI and player lateral size)
MaxVerticalDistance = AUTO                       ; Maximum vertical distance (game units) for boost growth (AUTO = Use AI and player vertical size)

[Debug]
UseSpeedbreakerBarAsSlingshotMeter = false       ; (EXPERIMENTAL) Displays the slingshot boost in the speedbreaker bar (true/1/on/yes = enabled, false/0/off/no = disabled)